spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## service1
        - id: service1
          uri: lb://auth-server
          predicates:
            - Path=/msauth/**
          filters:
            - StripPrefix=1

        ## Service2
        - id: service2
          uri: lb://task-manager-server
          predicates:
            - Path=/mstask/**
          filters:
            - StripPrefix=1
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: false
    fetchRegistry: false